### PR TITLE
#4 Turn blender-fake-addon project into blender-addon-tester importable Python package

### PR DESCRIPTION
**Pull request by myselfhimself**

### CODE REVIEW

**Comment by myselfhimself** [comment]
I have no clue yet how to fix the too many blender founds error within Travis. On the other side, the Github actions do work: see here: https://github.com/douglaskastle/blender-fake-addon/actions

**Comment by douglaskastle** [comment]
Hey man, great work so far. I am off all work at the moment so I can't look into this too much.

However, here is a case of lazy reporting on my part, there is either one correct blender found, or a fail, with the error message being deceptive. 

There is no blender returned, and the empty list is the list of all the blenders found, which is zero.

I am hoping to get some time over the next few days to look at this, I don't want you go way off on my, very loose, vision of how this this should work, or at least throw in my 2c.

**Comment by myselfhimself** [comment]
Github actions (coverage.xml artifacts & blender releases cache) & travisCI builds do work OK!!

**Comment by myselfhimself** [comment]
Seems mergeable to me, or maybe is some more documentation needed...

**Pull request merged**
